// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvcfjicmytjtxyclduer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2Y2ZqaWNteXRqdHh5Y2xkdWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwNDQxNjIsImV4cCI6MjA1NjYyMDE2Mn0.1-_hiNsyVPWO5kcrsrf-LrHkAgLwpR9YwEoPPql5blM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);